name: uz_tarix_test_app
description: "O'zbekiston eng yangi tarixi quiz app, sessiya uchun ishlab chiqilgan."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  macos:
    generate: true
    image_path: "lib/assets/Uzbekistan Flag.png"
  image_path: "lib/assets/Uzbekistan Flag.png"
  adaptive_icon_background: "#1E88E5"
  adaptive_icon_foreground: "lib/assets/Uzbekistan Flag.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/data/UZTarixTests.json
